services:
  api:
    build: .
    ports:
      - "4567:4567"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/birds
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    command: >
      bash -c "
      echo 'Waiting for PostgreSQL to be ready...'
      sleep 5 &&
      bundle exec rake db:migrate &&
      echo 'Starting API server...' &&
      bundle exec puma -p 4567 -b tcp://0.0.0.0
      "

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=birds
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  gem_cache:
